/* CONECTANDO A UM BANCO */

USE EMPRESA
GO

INSERT INTO ENDERECO VALUES('FLAMENGO', 'RJ', 1)
INSERT INTO ENDERECO VALUES('MORUMBI', 'SP', 2)
INSERT INTO ENDERECO VALUES('CENTRO', 'MG', 3)
INSERT INTO ENDERECO VALUES('CENTRO', 'SP', 4)
GO

SELECT *
FROM ENDERECO
GO

/* RELACIONAMENTO 1 X N */
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT,
	CHECK (TIPO IN('RES', 'COM', 'CEL'))
)
GO

INSERT INTO TELEFONE VALUES('CEL', '78998998', 1)
INSERT INTO TELEFONE VALUES('RES', '43125653', 1)
INSERT INTO TELEFONE VALUES('COM', '65433134', 2)
INSERT INTO TELEFONE VALUES('CEL', '24255461', 2)
GO

SELECT *
FROM ALUNO
GO

/* PEGAR DATA ATUAL */
SELECT GETDATE()
GO

/* CLAUSULA AMBIGUA */
SELECT A.NOME, T.TIPO, T.NUMERO, E.BAIRRO, E.UF
FROM ALUNO A
	INNER JOIN TELEFONE T
	ON A.IDALUNO = T.ID_ALUNO
	INNER JOIN ENDERECO E
	ON A.IDALUNO = E.ID_ALUNO
GO

/* USANDO LEFT JOIN PARA MOSTRAR TODOS OS ALUNOS */
SELECT A.NOME, T.TIPO, T.NUMERO, E.BAIRRO, E.UF
FROM ALUNO A
	LEFT JOIN TELEFONE T
	ON A.IDALUNO = T.ID_ALUNO
	INNER JOIN ENDERECO E
	ON A.IDALUNO = E.ID_ALUNO
GO

/* IF NULL */
SELECT	A.NOME,
		ISNULL(T.TIPO, 'SEM') AS 'TIPO',
		ISNULL(T.NUMERO, 'NUMERO') AS 'TELEFONE', 
		E.BAIRRO, 
		E.UF
FROM ALUNO A
	LEFT JOIN TELEFONE T
	ON A.IDALUNO = T.ID_ALUNO
	INNER JOIN ENDERECO E
	ON A.IDALUNO = E.ID_ALUNO
GO