/* TRABALHANDO COM DATAS */

USE EMPRESA
GO

SELECT *
FROM ALUNO
GO

SELECT NOME, NASCIMENTO
FROM ALUNO
GO

/* DATEDIFF - CALCULA A DIFERENÇA ENTRE 2 DATAS 
FUNÇÃO GETDATE() TRAZ DIA E HORA */
SELECT NOME, GETDATE() AS DIA_HORA
FROM ALUNO
GO

/* 1 PASSO */
SELECT NOME, DATEDIFF(DAY,NASCIMENTO,GETDATE()) AS 'IDADE'
FROM ALUNO
GO

/* 2 PASSO - RETORNO EM INTEIRO + OPERACAO MATEMATICA */
/* CALCULANDO POR DIA = DAY */
SELECT NOME, (DATEDIFF(DAY,NASCIMENTO,GETDATE())/365) AS 'IDADE'
FROM ALUNO
GO

/* CALCULANDO POR MES =  MONTH */
SELECT NOME, (DATEDIFF(MONTH,NASCIMENTO,GETDATE())/12) AS 'IDADE'
FROM ALUNO
GO

/* USANDO A FUNÇÃO POR ANO = YEAR */
SELECT NOME, DATEDIFF(YEAR,NASCIMENTO,GETDATE()) AS 'IDADE'
FROM ALUNO
GO

/* DATENAME - TRAZ O NOME DA PARTE DA DATA EM QUESTAO */
SELECT NOME, DATENAME(DAY,NASCIMENTO) AS 'DIA DE ANIVERSARIO'
FROM ALUNO
GO

SELECT NOME, DATENAME(MONTH,NASCIMENTO) AS 'MES DE ANIVERSARIO'
FROM ALUNO
GO

SELECT NOME, DATENAME(YEAR,NASCIMENTO) AS 'ANO DE ANIVERSARIO'
FROM ALUNO
GO

SELECT 	NOME, DATENAME(DAY,NASCIMENTO) AS 'DIA DE ANIVERSARIO',
		DATENAME(MONTH,NASCIMENTO) AS 'MES DE ANIVERSARIO',
		DATENAME(YEAR,NASCIMENTO) AS 'ANO DE ANIVERSARIO'
FROM ALUNO
GO

/* DATEPART - TRAZ O NOME DA PARTE DA DATA EM QUESTAO 
POREM O RETORNO É UM INTEIRO */
SELECT NOME, DATEPART(DAY,NASCIMENTO) AS 'DIA DE ANIVERSARIO'
FROM ALUNO
GO

SELECT NOME, DATEPART(MONTH,NASCIMENTO) AS 'MES DE ANIVERSARIO'
FROM ALUNO
GO

SELECT NOME, DATEPART(YEAR,NASCIMENTO) AS 'ANO DE ANIVERSARIO'
FROM ALUNO
GO

SELECT 	NOME, DATEPART(DAY,NASCIMENTO) AS 'DIA DE ANIVERSARIO',
		DATEPART(MONTH,NASCIMENTO) AS 'MES DE ANIVERSARIO',
		DATEPART(YEAR,NASCIMENTO) AS 'ANO DE ANIVERSARIO'
FROM ALUNO
GO

/* DATEADD - RETORNA UMA DATA SOMANDO OUTRA DATA */
SELECT DATEADD(DAY, 365, GETDATE())
GO

SELECT DATEADD(YEAR, 10, GETDATE())
GO

