/* CONVERSAO OU CONCATENAÇÃO DE DADOS */
SELECT 1 + '1'
GO

SELECT '1' + '1'
GO

SELECT 'CURSO DE BANDO DE DADOS' + '1'
GO

SELECT 'CURSO DE BANDO DE DADOS' + 1
GO

SELECT NOME, NASCIMENTO
FROM ALUNO
GO

/* FUNÇÕES DE CONVERSAO DE DADOS - FORÇANDO A CONVERSAO */
SELECT CAST('1' AS INT) + CAST('1' AS INT)
GO