/* FUNÇÃO CHARINDEX - RETORNA UM INTEIRO 
CONTAGEM DEFAULT - INICIA EM 01 */

USE EMPRESA
GO

/* BUSCANDO A EM QUALQUER POSIÇÃO */
SELECT NOME,
CHARINDEX('A', NOME) AS INDICE
FROM ALUNO

/* BUSCANDO A DEFININDO A POSIÇÃO INICIAL COMO 3 */
SELECT NOME,
CHARINDEX('A', NOME, 3) AS INDICE
FROM ALUNO