/* BULK INSERT COM CHARINDEX */

CREATE TABLE LANCAMENTO CONTABIL(
	CONTA INT,
	VALOR INT,
	DEB_CRED CHAR(1)
)
GO

/* \t = TAB É O DELIMITADOR DO ARQUIVO */
BULK INSERT LANCAMENTO_CONTABIL
FROM 'C:\Users\Alan Leonardo\Documents\Curso\SCRIPTS\SQLSERVER\CONTAS.txt'
WITH
(
	FIRSTROW = 2,
	DATAFILETYPE = 'CHAR',
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR = '\n'
)