/* SIMPLIFICANDO AS TRIGGERS */

USE EMPRESA
GO
SELECT 10 + 10

CREATE TABLE RESULTADO(
	IDRESULTADO INT PRIMARY KEY IDENTITY,
	RESULTADO INT
)
GO

INSERT INTO RESULTADO VALUES((SELECT 10 + 10))
GO

SELECT * FROM RESULTADO
GO

/* ATRIBUNDO SELECTS A VARIAVEIS - ANONIMO */
DECLARE 
	@RESULTADO INT
	SET @RESULTADO = (SELECT 50 + 50)
INSERT INTO RESULTADO 
VALUES(@RESULTADO)
PRINT 'VALOR INSERIDO NA TABELA: ' + CAST(@RESULTADO AS VARCHAR)
GO

/* TRIGGER UPDATE SIMPLIFICADA */
CREATE TABLE EMPREGADO(
	IDEMP INT PRIMARY KEY,
	NOME VARCHAR(30),
	SALARIO MONEY,
	IDGERENTE INT
)
GO

ALTER TABLE EMPREGADO
ADD CONSTRAINT FK_GERENTE
FOREIGN KEY(IDGERENTE)
	REFERENCES EMPREGADO(IDEMP)
GO

INSERT INTO EMPREGADO VALUES(1, 'CLARA', 5000.00, NULL)
INSERT INTO EMPREGADO VALUES(2, 'CELIA', 4000.00, 1)
INSERT INTO EMPREGADO VALUES(3, 'JOAO', 4000.00, 1)
GO

CREATE TABLE HIST_SALARIO(
	IDEMPREGADO INT,
	ANTIGOSAL MONEY,
	NOVOSAL MONEY,
	DATA DATETIME
)
GO

CREATE TRIGGER TRG_SALARIO
ON DBO.EMPREGADO
FOR UPDATE AS
IF UPDATE(SALARIO)
BEGIN
	INSERT INTO HIST_SALARIO(IDEMPREGADO, ANTIGOSAL, NOVOSAL, DATA)
	SELECT D.IDEMP, D.SALARIO, I.SALARIO, GETDATE()
	FROM DELETED D, inserted I
	WHERE D.IDEMP = I.IDEMP
END
GO