/* SIMPLIFICANDO AS TRIGGERS */

USE EMPRESA
GO

CREATE TABLE SALARIO_RANGE(
	MINSAL MONEY,
	MAXSAL MONEY
)
GO

INSERT INTO SALARIO_RANGE VALUES(2000.00, 6000.00)
GO

CREATE TRIGGER TRG_RANGE
ON DBO.EMPREGADO
FOR INSERT, UPDATE AS
	DECLARE
		@MINSAL MONEY, 
		@MAXSAL MONEY,
		@ATUALSAL MONEY
	SELECT @MINSAL = MINSAL, @MAXSAL = MAXSAL FROM SALARIO_RANGE
	SELECT @ATUALSAL = I.SALARIO FROM inserted I
IF(@ATUALSAL < @MINSAL)
	BEGIN
		RAISERROR('SALARIO MENOR QUE O PISO', 16,1)
		ROLLBACK TRANSACTION
	END
IF(@ATUALSAL > @MAXSAL)
	BEGIN
		RAISERROR('SALARIO MAIOR QUE O TETO', 16,1)
		ROLLBACK TRANSACTION
	END
GO

/* TESTANDO A TRIGGER */
UPDATE EMPREGADO
SET SALARIO = 9000.00
WHERE IDEMP = 1
GO

Mensagem 50000, Nível 16, Estado 1, Procedimento TRG_RANGE, Linha 257
SALARIO MAIOR QUE O TETO
Mensagem 3609, Nível 16, Estado 1, Linha 241
A transação foi encerrada no gatilho. O lote foi anulado.

UPDATE EMPREGADO
SET SALARIO = 1000.00
WHERE IDEMP = 1
GO

Mensagem 50000, Nível 16, Estado 1, Procedimento TRG_RANGE, Linha 326
SALARIO MENOR QUE O PISO
Mensagem 3609, Nível 16, Estado 1, Linha 315
A transação foi encerrada no gatilho. O lote foi anulado.

/* VERIFICANDO O TEXTO SCRIPT DA TRIGGER */
SP_HELPTEXT TRG_RANGE
GO