/* PROCEDURES - SP_ STORAGE PROCEDURES*/

USE EMPRESA
GO

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN('M', 'F')),
	NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONE(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK(TIPO IN('CEL', 'COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES('ANTONIO', 'M', '1981-02-13')
INSERT INTO PESSOA VALUES('DANIEL', 'M', '1985-03-18')
INSERT INTO PESSOA VALUES('CLEIDE', 'F', '1979-10-13')
GO

INSERT INTO TELEFONE VALUES('CEL', '9831232', 1)
INSERT INTO TELEFONE VALUES('COM', '3231315', 1)
INSERT INTO TELEFONE VALUES('CEL', '9431212', 2)
INSERT INTO TELEFONE VALUES('CEL', '8831222', 2)
INSERT INTO TELEFONE VALUES('COM', '3231232', 3)
INSERT INTO TELEFONE VALUES('COM', '3231298', 2)
INSERT INTO TELEFONE VALUES('CEL', '9031254', 3)
GO

/* CRIANDO A PROCEDURE ESTÁTICA */
CREATE PROC SOMA
AS
	SELECT 10 + 10 AS SOMA
GO

/* EXECUTANDO A PROCEDURE */
EXEC SOMA
GO

/* CRIANDO A PROCEDURE COM PARAMETROS */
CREATE PROC CONTA @NUM1 INT, @NUM2 INT
AS
	SELECT @NUM1 + @NUM2
GO

/* EXECUTANDO A PROCEDURE */
EXEC CONTA 90, 78
GO

/* APAGANDO A PROCEDURE */
DROP PROC CONTA
GO

/* CRIANDO A PROCEDURE EM TABELAS */
SELECT NOME, NUMERO
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

/* PROCEDURE - TRAZER OS TELEFONES DE ACORDO COM O TIPO PASSADO */
CREATE PROC TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO
	FROM PESSOA
	INNER JOIN TELEFONE
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO
GO

EXEC TELEFONES 'CEL'
GO

EXEC TELEFONES 'COM'
GO

/* PARAMETROS DE OUTPUT */
SELECT TIPO, COUNT(*) AS QUANTIDADE
FROM TELEFONE
GROUP BY TIPO
GO

CREATE PROC GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE
	WHERE TIPO = @TIPO
GO

/* EXECUCAO DA PROC COM PARAMETRO DE SAIDA */
DECLARE @SAIDA INT
EXEC GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO

DECLARE @SAIDA INT
EXEC GETTIPO 'CEL', @SAIDA OUTPUT
SELECT @SAIDA
GO