/* TSQL - BLOCOS IF E ELSE */

USE EMPRESA
GO

DECLARE @NUMERO INT = 5
BEGIN
	IF @NUMERO = 5 --EXPRESSAO BOOLEANA
		PRINT 'O VALOR É VERDADEIRO'
	ELSE
		PRINT 'O VALOR É FALSO'
END
GO

/* CASE */
DECLARE	@CONTADOR INT
BEGIN
	SELECT -- O CASE REPRESENTA UMA COLUNA
	CASE
		WHEN FABRICANTE = 'FIAT' 
			THEN 'FAIXA 1'
		WHEN FABRICANTE = 'CHEVROLET' 
			THEN 'FAIXA 2'
	ELSE 'OUTRAS FAIXAS'
END AS 'INFORMAÇÕES',
*
FROM CARROS
END
GO