/* EXERCICIO 01 - CONVERTER E CONCATENAR AS DATAS */

/* USANDO A FUNÇÃO DATANAME PRA DEIXAR AS DATAS EM VARCHAR */
SELECT 	NOME,
		DATENAME(DAY,NASCIMENTO) + '/' +
		DATENAME(MONTH,NASCIMENTO)  + '/' +
		DATENAME(YEAR,NASCIMENTO) AS 'DATA DE ANIVERSARIO'
FROM ALUNO

NOME	DATA DE ANIVERSARIO
ANDRE	30/Dezembro/1999
CARLOS	15/Abril/2002
MARIA	22/Setembro/1989
JULIA	15/Janeiro/1995

/* USANDO A FUNÇÃO CAST PRA FORÇAR AS DATAS EM VARCHAR */
SELECT 	NOME,
		CAST(DAY(NASCIMENTO) AS VARCHAR) + '/' +
		CAST(MONTH(NASCIMENTO) AS VARCHAR) + '/' +
		CAST(YEAR(NASCIMENTO) AS VARCHAR) AS 'NASCIMENTO'
FROM ALUNO

NOME	NASCIMENTO
ANDRE	30/12/1999
CARLOS	15/4/2002
MARIA	22/9/1989
JULIA	15/1/1995