USE EMPRESA1
GO

-- TABELA GRADE

CREATE TABLE Tamanhos(
	Tamanho_ID INT PRIMARY KEY IDENTITY,
	Tamanho_Descricao VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Grades(
	Grade_ID INT PRIMARY KEY IDENTITY,
	Grade_Descricao VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Grades_Tamanhos(
	GraTam_ID INT PRIMARY KEY IDENTITY,
	Grade_ID INT NOT NULL,
	Tamanho_ID INT NOT NULL
)
GO

ALTER TABLE Grades_Tamanhos
ADD FOREIGN KEY (Grade_ID) REFERENCES Grades(Grade_ID)
GO

ALTER TABLE Grades_Tamanhos
ADD FOREIGN KEY (Tamanho_ID) REFERENCES Tamanhos(Tamanho_ID)
GO

-- TABELA CLASSIFICAÇÃO

CREATE TABLE Grupos(
	Grupo_ID INT PRIMARY KEY IDENTITY,
	Grupo_Descricao VARCHAR(50) NOT NULL
)
GO

CREATE TABLE SubGrupos(
	SubGrupo_ID INT PRIMARY KEY IDENTITY,
	SubGrupo_Descricao VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Grupos_SubGrupos(
	GruSub_ID INT PRIMARY KEY IDENTITY,
	Grupo_ID INT NOT NULL,
	SubGrupo_ID INT NOT NULL
)
GO

ALTER TABLE Grupos_SubGrupos
ADD FOREIGN KEY (Grupo_ID) REFERENCES Grupos(Grupo_ID)
GO

ALTER TABLE Grupos_SubGrupos
ADD FOREIGN KEY (SubGrupo_ID) REFERENCES SubGrupos(SubGrupo_ID)
GO

-- TABELA PREÇOS

CREATE TABLE Tabelas(
	Tabela_ID INT PRIMARY KEY IDENTITY,
	Tabela_Descricao VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Tabelas_Valores(
	Valor_ID INT PRIMARY KEY IDENTITY,
	Produto_ID INT NOT NULL,
	Tabela_ID INT NOT NULL,
	Valor_Venda NUMERIC(10,2) NOT NULL
)
GO

ALTER TABLE Tabelas_Valores
ADD FOREIGN KEY (Tabela_ID) REFERENCES Tabelas(Tabela_ID)
GO

-- TABELA ESTOQUE

CREATE TABLE Estoques_Grades(
	EstGra_ID INT PRIMARY KEY IDENTITY,
	GraTam_ID INT NOT NULL,
	EstGra_Quantidade INT NOT NULL
)
GO

ALTER TABLE Estoques_Grades
ADD FOREIGN KEY (GraTam_ID) REFERENCES Grades_Tamanhos(GraTam_ID)
GO

-- TABELA PRODUTOS

CREATE TABLE Produtos(
	Produto_ID INT PRIMARY KEY IDENTITY,
	Produto_Descricao VARCHAR(50) NOT NULL,
	GruSub_ID INT NOT NULL,
	GraTam_ID INT NOT NULL,
	Valor_ID INT NOT NULL,
	EstGra_ID INT NOT NULL
)
GO

ALTER TABLE Produtos
ADD FOREIGN KEY (GruSub_ID) REFERENCES Grupos_SubGrupos(GruSub_ID)
GO

ALTER TABLE Produtos
ADD FOREIGN KEY (GraTam_ID) REFERENCES Grades_Tamanhos(GraTam_ID)
GO

ALTER TABLE Produtos
ADD FOREIGN KEY (Valor_ID) REFERENCES Tabelas_Valores(Valor_ID)
GO

ALTER TABLE Produtos
ADD FOREIGN KEY (EstGra_ID) REFERENCES Estoques_Grades(EstGra_ID)