-- TABELA IMPOSTOS IPI

CREATE TABLE Ipi_Impostos(
	Ipi_ID INT PRIMARY KEY IDENTITY,
	Produto_ID INT NOT NULL,
	Ipi_Alíquota DECIMAL(10,2)
)
GO

ALTER TABLE IPI_Impostos
ADD FOREIGN KEY (Produto_ID) REFERENCES Produtos(Produto_ID)
GO

-- TABELA IMPOSTOS ICMS ST
CREATE TABLE IcmsSt_Impostos(
    IcmsST_ID INT PRIMARY KEY,
    Produto_ID INT NOT NULL,
    Mva DECIMAL(10,2) NOT NULL,
    Alíquota_ICMS DECIMAL(10,2) NOT NULL
);

ALTER TABLE ICMSST_Impostos
ADD FOREIGN KEY (Produto_ID) REFERENCES Produtos(Produto_ID)
GO