--APENAS CHECKANDO QUAL A SEQUÊNCIA IDENTITY ATUAL DA PRIMARY KEY
DBCC CHECKIDENT ('LANCAMENTOS')
DBCC CHECKIDENT ('ENTRADAS')
DBCC CHECKIDENT ('SAIDAS')
DBCC CHECKIDENT ('CATEGORIAS')

--CHECKANDO SEQUENCIA DA IDENTIFY DA PRIMARY KEY E ALTERANDO PARA 0
DBCC CHECKIDENT ('LANCAMENTOS', RESEED, 0)
DBCC CHECKIDENT ('ENTRADAS', RESEED, 0)
DBCC CHECKIDENT ('SAIDAS', RESEED, 0)
DBCC CHECKIDENT ('CATEGORIAS', RESEED, 0)
GO

-- DELETANDO LINHA POR LINHA
DELETE FROM ENTRADAS
WHERE ID_ENTRADA = 1
GO

-- DELETANDO VÁRIAS LINHAS DE UMA VEZ SÓ
DELETE FROM ENTRADAS
WHERE ID_ENTRADA 
	BETWEEN 1 AND 10
GO

DELETE FROM SAIDAS
WHERE ID_SAIDA 
	BETWEEN 1 AND 10
GO

DELETE FROM CATEGORIAS
WHERE IDCATEGORIA
	BETWEEN 1 AND 10
GO

--TESTANDO VISUALIZAÇÃO DOS DADOS
SELECT *
FROM ENTRADAS
GO

SELECT *
FROM SAIDAS
GO

SELECT *
FROM LANCAMENTOS
GO

SELECT *
FROM CATEGORIAS
GO
