/* SELECT *
FROM CATEGORIAS
GO */

-- AO IMPORTAR, CUIDAR COM O CAMPO ESTRUTURA, POIS ALGUNS VALORES PODEM NÃO IMPORTAR CORRETAMENTE DEVIDO AO ZERO NO INICIO DO VALOR
BULK INSERT CATEGORIAS
FROM 'C:\Users\Admin\Documents\Alan\BI\POWER BI\PROJETOS\Projeto4-DRE_FLUXODECAIXA\DREEstrutura.csv'
WITH (
	FIRSTROW = 2,
	KEEPIDENTITY,
	CODEPAGE = '1252',
	FIELDTERMINATOR = ';',
	ROWTERMINATOR = '0x0a'
);
GO
