SELECT *
FROM LANCAMENTOS
GO

--APENAS CHECKANDO QUAL A SEQUÊNCIA IDENTITY ATUAL DA PRIMARY KEY
DBCC CHECKIDENT ('LANCAMENTOS')
DBCC CHECKIDENT ('ENTRADAS')
DBCC CHECKIDENT ('SAIDAS')
DBCC CHECKIDENT ('CATEGORIAS')

--CHECKANDO SEQUENCIA DA IDENTIFY DA PRIMARY KEY E ALTERANDO PARA 0
DBCC CHECKIDENT ('LANCAMENTOS', RESEED, 0)
DBCC CHECKIDENT ('ENTRADAS', RESEED, 0)
DBCC CHECKIDENT ('SAIDAS', RESEED, 0)
GO

BULK INSERT LANCAMENTOS
FROM 'C:\Users\Admin\Documents\Alan\BI\POWER BI\PROJETOS\Projeto4-DRE_FLUXODECAIXA\Dados.csv'
WITH (
	FIRSTROW = 2,
	KEEPIDENTITY, 
	FIELDTERMINATOR = ';', 
	ROWTERMINATOR = '0x0a', 
	FIRE_TRIGGERS);
GO
