/* SCRIPT IMPORTANTE APENAS PARA VERIFICAÇÃO DE LANÇAMENTOS INCORRETOS (EVITAR LANÇAMENTOS DE ENTRADAS EM CONTAS DE SAÍDAS, 
VICE VERSA E EVITAR LANÇAMENTOS DE ENTRADA E SAIDA EM CONTAS QUE SÃO AMBOS(AMBOS SÃO CONTAS CALCULADAS)) */
/*SELECT C.ESTRUTURA, C.PLANODECONTAS, C.TIPO, L.VALOR
FROM LANCAMENTOS L
INNER JOIN CATEGORIAS C
ON L.PLANODECONTAS = C.IDCATEGORIA
ORDER BY 1;
GO */

-- AO UTILIZAR INNER JOIN, O SCRIPT IRÁ DESCONSIDERAR VALORES NULOS
/* SELECT C.ESTRUTURA, C.PLANODECONTAS, C.TIPO, SUM(L.VALOR) as 'TOTAL'
FROM LANCAMENTOS L
INNER JOIN CATEGORIAS C
ON L.PLANODECONTAS = C.IDCATEGORIA
GROUP BY C.ESTRUTURA, C.PLANODECONTAS, C.TIPO
ORDER BY 1;
GO */

/* AO UTILIZAR RIGHT JOIN, Isso fará com que todas as linhas da tabela à direita (no caso, CATEGORIAS) 
sejam incluídas no resultado, independentemente de haver ou não correspondência na tabela à esquerda (LANCAMENTOS)*/
SELECT C.ESTRUTURA, C.PLANODECONTAS, C.TIPO, SUM(L.VALOR) as 'TOTAL'
FROM LANCAMENTOS L
RIGHT JOIN CATEGORIAS C
ON L.PLANODECONTAS = C.IDCATEGORIA
GROUP BY C.ESTRUTURA, C.PLANODECONTAS, C.TIPO
ORDER BY 1;
GO