SELECT *
FROM LANCAMENTOS
GO

--APENAS CHECKANDO QUAL A SEQUÊNCIA IDENTITY ATUAL DA PRIMARY KEY
DBCC CHECKIDENT ('LANCAMENTOS')
DBCC CHECKIDENT ('ENTRADAS')
DBCC CHECKIDENT ('SAIDAS')
DBCC CHECKIDENT ('CATEGORIAS')

--CHECKANDO SEQUENCIA DA IDENTIFY DA PRIMARY KEY E ALTERANDO PARA 0
DBCC CHECKIDENT ('LANCAMENTOS', RESEED, 1000)
DBCC CHECKIDENT ('ENTRADAS', RESEED, 242)
DBCC CHECKIDENT ('SAIDAS', RESEED, 257)
GO

BULK INSERT LANCAMENTOS
FROM 'C:\Users\Admin\OneDrive\Documentos\Alan\BI\POWER BI\PROJETOS\Projeto4-DRE_FLUXODECAIXA\Dados2.csv'
WITH (
	FIRSTROW = 2,
	KEEPIDENTITY, 
	FIELDTERMINATOR = ';', 
	ROWTERMINATOR = '0x0a', 
	FIRE_TRIGGERS);
GO